### ISSUE TITLE
latest version of mtinside/envbin fails to show the Liveness, Readiness etc selections at the bottom

### ISSUE THREAD

**Issue by pjiocnic** [mt-inside/envbin#31]
12222020:  I just pulled the latest version of https://hub.docker.com/r/mtinside/envbin as I was working thru' your course I noticed the selections (for Quit, Liveness, readiness Latency, Bandwidth and error rate) are no longer available at the bottom of http://envbin.example.com/ page.  This used to work in your previous version

**Comment by mt-inside** [comment]
Hi! Thanks for the report, yes you're right! I was working on this project for personal reasons, forgot it was used in the course!

In the immediate term, that functionality has been split out into https://github.com/mt-inside/badpod / https://hub.docker.com/repository/docker/mtinside/badpod. That should work fine.

When I get a chance I'll put this project back how it was and do my development somewhere else, sorry for the inconvenience.

I've been staring at 12222020 a lot... it's and American-style date?

**Comment by pjiocnic** [comment]
Yes, from the superior American english 👍. I still think COLOR is shorter and sweeter - COLOUR vs COLOR :-)

Thanks for the great course!!!  You have introduced concepts that makes the course very unique and engaging!

**Comment by pjiocnic** [comment]
Sorry, https://hub.docker.com/repository/docker/mtinside/badpod is failing 

```
docker pull mtinside/badpod
Using default tag: latest
Error response from daemon: manifest for mtinside/badpod:latest not found: manifest unknown: manifest unknown
```

**Comment by mt-inside** [comment]
Haha I'll give you color, and all those Z's, but dates should be ascending or descending, otherwise they're ambiguous! I was just checking it wasn't a commit tag or something ;)

Ah sorry, badpod should be fixed now - my CI system was so "advanced" there wasn't a `latest` tag, but I've added one now.

Thanks for the feedback on the course btw, I don't really get i normally. I'm so glad you like it!
